debug: false
uuid: cea92071-b1ef-4b0d-82e8-175d48fe281d
token_id: WRrpsyaCztOvYNe0
token: AVjLnqR2RVjtRU6qznUpVUX0fpoZ83k1HE6BGkniVPuU0pwCN5xf2ZMqmvIkwZBV
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/certs/fullchain.pem
    key: /etc/certs/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.lenoxhosting.dpdns.org'
