debug: false
uuid: 92845604-1256-4657-9171-101b0ff4d6f7
token_id: 4mWDGPv1sLezazsY
token: 0GwSjftSpYj0zAFQ2byS1CqYePHVznkr2h4o6PLxKJmvZGgXsRF8D4WQsB8JULyQ
api:
  host: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    cert: /etc/certs/fullchain.pem
    key: /etc/certs/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.xerohosting.dpdns.org'
docker:
  network:
    interface: 172.17.0.10
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: pterodactyl_nw
    ispn: false
    driver: bridge
    network_mode: pterodactyl_nw
    is_internal: false
    enable_icc: true
    interfaces:
      v4:
        subnet: 172.17.0.0/16
        gateway: 172.17.0.10
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
```
