debug: false
uuid: d8a06e5a-035e-4144-bc48-bf4d5a6dfdbb
token_id: 4ouycYMaBFuprzTv
token: Jf1DCwHVB0yzGyIQpV54HQ0LOtRGaZa1ZobTae2WUCTHwOi2n93rbPF8utzwa2nS
api:
  host: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    cert: /etc/certs/fullchain.pem
    key: /etc/certs/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/Jexactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.xerohosting.dpdns.org'
