debug: false
uuid: c93422ad-df97-4cf7-be89-62e1bc6e2661
token_id: qulQ4kDv51cVfMXU
token: Ws4XQx1RWUv4qL5zlCdjVfboQdPsNBB60RSYxgkPqxhtbJCcWXHXvTWuZ0Ci7bJS
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/node.hostdechoi.dpdns.org/fullchain.pem
    key: /etc/letsencrypt/live/node.hostdechoi.dpdns.org/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.hostdechoi.dpdns.org'
