debug: false
uuid: 402df74b-37e1-44ff-b5f4-f507ff03eb22
token_id: 9RPiTghUqCtsvnrd
token: vwRZCB3rGoQYJp694pbcOFCBYeA2SY3GS3rsYjTOeGIRDqaI9IODfNEIGrnE3xtk
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/a7bd5c602b4a8a36b5fcf23b042d0a65.serveo.net/fullchain.pem
    key: /etc/letsencrypt/live/a7bd5c602b4a8a36b5fcf23b042d0a65.serveo.net/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://59748b473b02dffc4c2512f9a549f455.serveo.net'
